name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build GUI executable
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "FileSynchronizer_GUI" --icon "icon.ico" --add-data "assets;assets" gui.py
      
      - name: Build CLI executable
        run: |
          pyinstaller --noconfirm --onefile --name "FileSynchronizer_CLI" --icon "icon.ico" cli.py

      - name: Prepare package for release
        run: |
          mkdir release_package
          copy dist\*.exe release_package\
          copy *.ini.example release_package\
          copy README.md release_package\
          xcopy assets release_package\assets\ /E /I
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FileSynchronizer-Windows
          path: release_package/